management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  datadog:
    metrics:
      export:
        api-key: ${DD_API_KEY}
        enabled: true
        application-name: kosha-microservices-app
        step: 30s
    tags:
      env: dev

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: clifortramaramela@gmail.com
    password: dhxx myhx ujzx gzbk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${MY_SQL_DB_URL}
    username: ${MY_SQL_DB_USERNAME}
    password: ${MY_SQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: create
