name: IntelliJ Agent - Gradle Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
#      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        run: ./gradlew --version
        working-directory: /

      - name: Run Tests
        run: ./gradlew test
        working-directory: /

      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p gradle/.qodana/code-coverage
          cp -R gradle/build/kover/bin-reports/* gradle/.qodana/code-coverage/

      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: gradle-coverage-data.zip
          path: /gradle/.qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "-i,gradle,--linter,jetbrains/qodana-jvm:2023.2-eap"
          pr-mode: false