name: Deploy to Dev Green Slot (Docker Blue-Green)

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  IMAGE_NAME: kosha-microservices-app
  IMAGE_TAG: dev-green-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: zulu

      - name: Build Spring Boot JAR
        run: ./gradlew clean build

      - name: Download Datadog Java Agent
        run: curl -L -o dd-java-agent.jar https://dtdg.co/latest-java-tracer

      - name: Copy JAR for Docker
        run: cp build/libs/sage-microservices-0.0.1-SNAPSHOT.jar app.jar

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_SIT }}
          slot-name: dev-passive
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
