name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradlew
        run: |
          chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t kosha10111/springboot-microservices .

      - name: Publish image to docker hub
        run: docker push kosha10111/springboot-microservices

  deploy:
    needs: build
    runs-on: [ aws-ec2 ]
    steps:

      - name: Pull Image from docker hub
        run: docker pull kosha10111/springboot-microservices

      - name: Delete old container
        run: docker rm -f sspringboot-microservices

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-microservies kosha10111/springboot-microservices
