name: Build
'on': pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission to Gradlew
        run: |
          chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test