name: Build Gradle

on:
  push:
    branches: [master, deploy-to-prod]
  pull_request:
    branches: [master, deploy-to-prod]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          coverage:
            range: 75...100
          flags:
            - analytics
          fail_ci_if_error: true # optional (default = false)
          files: ./build/reports/jacoco/test/jacocoTestReport.xml # optional
        #          flags: unittests # optional
        #          name: codecov-umbrella # optional
        #          verbose: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}